<a href="https://colab.research.google.com/github/tannyyaawadhwani-design/puthony/blob/main/day1py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Integer
age = 22
print(type(age))

# Float
height = 165.5
print(type(height))


# String
name = "Tanya"
print(type(name))

# Boolean
is_student = True
print(type(is_student))


# string operation
text = "data science"
print(text.upper())     # Uppercase
print(text.lower())     # Lowercase
print(text.title())     # Title Case
print(text.replace("data", "machine"))  # Replace words
print("science" in text)  # Check if contains word → True/False


# loops

# For loop
for i in range(1, 6):
    print(f"Number: {i}")

# While loop
count = 0
while count < 3:
    print("Hello")
    count += 1

# dictionary
student = {
    "name": "Tanya",
    "age": 22,
    "course": "Data Science"
}

print(student["name"])      # Access value
student["age"] = 23         # Update value
student["city"] = "Raipur"  # Add new key-value
print(student)


# list add insert delete sort


fruits = ["apple", "banana", "cherry"]

# Add
fruits.append("mango")
print(fruits)

# Insert at position
fruits.insert(1, "orange")
print(fruits)

# Remove by value
fruits.remove("banana")
print(fruits)

# Remove last item
fruits.pop()
print(fruits)

# Sort
fruits.sort()
print(fruits)



#list comprehension

# Traditional way
squares = []
for i in range(1, 6):
    squares.append(i * i)
print(squares)

# List comprehension
squares = [i * i for i in range(2, 9)]
print(squares)



#learn if elif else

marks = 85

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
else:
    print("Grade: C")



# learn   Functions with Parameters & Defaults

def greet(name, msg="Welcome to Data Science"):
    print(f"Hello {name}, {msg}")

greet("Tanya")
greet("Ravi", "Good luck with Python!")



# learn importing modules

import math

print(math.sqrt(25))    # Square root
print(math.pi)          # π value
print(math.factorial(5))# Factorial

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
DATA SCIENCE
data science
Data Science
machine science
True
Number: 1
Number: 2
Number: 3
Number: 4
Number: 5
Hello
Hello
Hello
Tanya
{'name': 'Tanya', 'age': 23, 'course': 'Data Science', 'city': 'Raipur'}
['apple', 'banana', 'cherry', 'mango']
['apple', 'orange', 'banana', 'cherry', 'mango']
['apple', 'orange', 'cherry', 'mango']
['apple', 'orange', 'cherry']
['apple', 'cherry', 'orange']
[1, 4, 9, 16, 25]
[4, 9, 16, 25, 36, 49, 64]
Grade: B
Hello Tanya, Welcome to Data Science
Hello Ravi, Good luck with Python!
5.0
3.141592653589793
120