<a href="https://colab.research.google.com/github/tannyyaawadhwani-design/puthony/blob/main/day5py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
#student info
students=pd.DataFrame({"id": [1,2,3,4], "name": ["tanya","shivani","rishi","shubham"]})
print(students,"\n")

#student marks
marks=pd.DataFrame({"id":[1,2,3,5], "marks":[99,88,64,78]})
print(marks,"\n")

#merge on id
merged_df=pd.merge(students,marks, on="id", how="inner")
print(merged_df,"\n")

merged_df=pd.merge(students,marks, on="id", how="outer")
print(merged_df,"\n")

merged_df=pd.merge(students,marks, on="id", how="left")
print(merged_df,"\n")

merged_df=pd.merge(students,marks, on="id", how="right")
print(merged_df,"\n")

#company employees and salary
#employees table
employees=pd.DataFrame({"empid":[101,102,103,104],"name":["tanya","shivani","rishi","shubham"],
                        "department":["HR","IT","Finance","IT"]})

#salaries table
salaries=pd.DataFrame({"empid":[101,102,105],"salary":[50000,60000,55000]})

print(pd.merge(employees,salaries, on="empid", how="inner"),"\n")
print(pd.merge(employees,salaries, on="empid", how="left"),"\n")
print(pd.merge(employees,salaries, on="empid", how="outer"),"\n")
# Table 1
projects = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "Department": ["HR", "IT", "Finance", "IT"],
    "Project": ["Hiring", "Website", "Audit", "App"]
})
print(projects,"\n")

# Table 2
performance = pd.DataFrame({
    "EmpID": [101, 102, 104, 105],
    "Department": ["HR", "IT", "IT", "Sales"],
    "Score": [90, 85, 92, 88]
})
print(performance,"\n")

# Merge on EmpID and Department
merged = pd.merge(projects, performance, on=["EmpID", "Department"], how="inner")
print(merged,"\n")
merged = pd.merge(projects, performance, on=["EmpID", "Department"], how="outer")
print(merged,"\n")


# Left DataFrame
employees = pd.DataFrame({
    "Department": ["HR", "IT", "Finance"],
    "Manager": ["Tanya", "Shivani", "Rishi"]
})

# Right DataFrame
salaries = pd.DataFrame({
    "Department": ["HR", "IT", "Finance"],
    "AvgSalary": [50000, 60000, 55000]
})

# ❌ merge needs explicit key
print(pd.merge(employees, salaries, on="Department", how="inner"), "\n")

# ✅ join works directly on index (so set Department as index)
employees_indexed = employees.set_index("Department")
salaries_indexed = salaries.set_index("Department")

print(employees_indexed.join(salaries_indexed),"\n")

#join on student table setting id as index
students_indexed = students.set_index("id")
marks_indexed = marks.set_index("id")

print(students_indexed.join(marks_indexed),"\n")

import pandas as pd
#detection of missing data
data = {
    "Name": ["Tanya", "Shivani", "Rishi", "Shubham", None],
    "Marks": [99, 88, None, 66, 55],
    "Subject": ["Python", "Java", "Python", None, "SQL"]
}

df = pd.DataFrame(data)
print(df,"\n")
print(df.isna(),"\n")   # Shows True where values are missing
print(df.notna(),"\n")  # Shows True where values exist
print(df.isna().sum(),"\n")  # Count of missing values in each column

#Handling missing Data
#Dropna delete the row with missing data nan
print(df.dropna,"\n")

#fillna fill the missing DataNAN with unknown
print(df.fillna,"\n")

#another Fillna fill the nan data with column statistic COMMOM WHEN NUMBERS
print(df["Marks"].fillna(df["Marks"].mean()),"\n")

#filling missing in categoical column
df["Name"]=df["Name"].fillna("unknown")
df["Subject"]=df["Subject"].fillna("not provided")
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
print(df,"\n")


#filtering with multiple conditions
print(df[(df["Marks"] > 70) & (df["Subject"] == "Python")],"\n")
print(df[(df["Marks"] > 80) & (df["Subject"] == "SQL")],"\n")
print(df[(df["Marks"] < 80) & (df["Subject"] == "Python")],"\n")

#filter using isi()
print(df[df["Subject"].isin(["Python","SQL"])],"\n")

#sql like filtering with .query()
print(df.query("Marks > 80 and Subject == 'Python' "),"\n")
print(df.query("Marks >=60 or Subject == 'SQL' "),"\n")

#removing duplicates